version: '3.8'

services:
  db:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avito_shop
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data

  app:
    build: .
    container_name: my_avito_app
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: avito_shop
      JWT_SECRET: avitomiraines
    depends_on:
      - db
